default_platform(:ios)

platform :ios do
  desc "Build iOS app with Match"
  lane :build do
    match(
      type: "appstore",
      readonly: true # CI/CD should use readonly mode
    )
    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )
  end
end
