default_platform(:ios)

platform :ios do
  desc "Build the iOS app"
  lane :build do
    match(type: "appstore") # Optional: use match to pull certificates/profiles automatically
    build_app(
      scheme: "Runner", # Flutter uses Runner.xcworkspace
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          ENV["IOS_BUNDLE_IDENTIFIER"] => "YourProvisioningProfileName"
        },
        teamID: ENV["IOS_TEAM_ID"]
      }
    )
  end
end
