name: Flutter Build (iOS and Android)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- name: Set up Flutter
      #  uses: subosito/flutter-action@v2
      #  with:
      #    flutter-version: '3.29.3'  # Your Flutter version
      #    cache: true

      #- name: Install Flutter dependencies
      #  run: flutter pub get

      - name: Print info
        env:
          IOS_BUNDLE_IDENTIFIER: ${{ secrets.IOS_BUNDLE_IDENTIFIER }}
        run: |
          echo $IOS_BUNDLE_IDENTIFIER 

      #- name: Set up keychain and certificate
      #  run: |
      #    # Create a temporary keychain
      #    security create-keychain -p "" build.keychain
      #    security default-keychain -s build.keychain
      #    security unlock-keychain -p "" build.keychain
      #    security set-keychain-settings build.keychain

      #    # Decode and import the certificate
      #    echo $IOS_CERTIFICATE_BASE64 | base64 --decode
      #    echo $IOS_CERTIFICATE_BASE64 | base64 --decode > certificate.p12
      #    security import certificate.p12 -P "$IOS_CERTIFICATE_PASSWORD" -A

      #    # Allow codesign to access the keychain
      #    security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      #- name: Install provisioning profile
      #  run: |
      #    mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
      #    echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/adhoc.mobileprovision

      #- name: Build IPA
      #  run: |
      #    flutter build ipa --release --export-options-plist=ios/ExportOptions.plist


      # Upload iOS IPA artifact
      #- name: Upload IPA artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ios-adhoc-ipa
      #    path: build/ios/ipa/*.ipa

      #- name: Build Android APK
      #  run: flutter build apk --release

      #- name: Build Android AAB
      #  run: flutter build appbundle --release

      #- name: Upload Android APK
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: app-release.apk
      #    path: build/app/outputs/flutter-apk/app-release.apk

      #- name: Upload Android AAB
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: app-release.aab
      #    path: build/app/outputs/bundle/release/app-release.aab
