name: Flutter Build (iOS and Android)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # Your Flutter version
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      #- name: Build Android APK
      #  run: flutter build apk --release

      #- name: Build Android AAB
      #  run: flutter build appbundle --release

      # Set up Ruby (for Fastlane)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      # Install Fastlane
      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      # Set up Signing
      - name: Set up signing certificates and provisioning profiles
        run: |
          mkdir -p ~/certs
          echo "${{ secrets.IOS_CERTIFICATE_BASE64 }}" | base64 --decode > ~/certs/ios_certificate.p12
          echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/certs/profile.mobileprovision


      # Run Fastlane
      - name: Build iOS IPA with Fastlane
        run: fastlane ios build

      #- name: Upload Android APK
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: app-release.apk
      #    path: build/app/outputs/flutter-apk/app-release.apk

      #- name: Upload Android AAB
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: app-release.aab
      #    path: build/app/outputs/bundle/release/app-release.aab

      # Upload iOS IPA artifact
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-release.ipa
          path: build/ios/ipa/*.ipa
